#!/bin/sh

. ./image-env.sh

docker tag ${PROJECT_ID}-${ARTIFACT_ID}:${GIT_HASH} $REGISTRY/$REGISTRY_USER_ID/${PROJECT_ID}-${ARTIFACT_ID}:${GIT_HASH}
docker tag ${PROJECT_ID}-${ARTIFACT_ID}:${GIT_HASH} $REGISTRY/$REGISTRY_USER_ID/${PROJECT_ID}-${ARTIFACT_ID}:${ARTIFACT_VERSION}

docker push $REGISTRY/$REGISTRY_USER_ID/${PROJECT_ID}-${ARTIFACT_ID}:${GIT_HASH}
docker push $REGISTRY/$REGISTRY_USER_ID/${PROJECT_ID}-${ARTIFACT_ID}:${ARTIFACT_VERSION}